[package]
name = "tpt20-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Native binary wire format and core runtime for tpt20"

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tpt20-json = { path = "../tpt20-json" }
