//! Java backend: one class per message/enum/oneof plus `Tpt20Runtime`.

use crate::model::{Card, Enum, Field, Message, Model, Scalar, Ty};
use crate::naming::{avoid, package_ident, pascal};
use crate::{Backend, BackendError, BackendOptions, GeneratedFile};
use std::fmt::Write;
use tpt20_ir as ir;

const RUNTIME: &str = include_str!("runtime/Tpt20Runtime.java");

const KEYWORDS: &[&str] = &[
    "abstract",
    "assert",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extends",
    "final",
    "finally",
    "float",
    "for",
    "goto",
    "if",
    "implements",
    "import",
    "instanceof",
    "int",
    "interface",
    "long",
    "native",
    "new",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "strictfp",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "try",
    "void",
    "volatile",
    "while",
    "true",
    "false",
    "null",
    "var",
    "record",
    "yield",
    // Members every generated class defines.
    "encode",
    "decode",
    "decodeFrom",
    "unknownFields",
    "equals",
    "hashCode",
    "toString",
    "getClass",
    "notify",
    "notifyAll",
    "wait",
    "clone",
    "finalize",
];

/// Java code generator.
#[derive(Debug, Clone, Copy, Default)]
pub struct JavaBackend;

impl Backend for JavaBackend {
    fn name(&self) -> &'static str {
        "java"
    }

    fn generate(
        &self,
        package: &ir::PackageIr,
        options: &BackendOptions,
    ) -> Result<Vec<GeneratedFile>, BackendError> {
        let model = Model::build(package)?;
        let pkg = options
            .package_name
            .clone()
            .unwrap_or_else(|| package_ident(&model.package, "schema"));
        let g = Gen {
            model: &model,
            pkg: &pkg,
        };
        let mut files = vec![GeneratedFile {
            path: format!("{pkg}/Tpt20Runtime.java"),
            contents: RUNTIME.replace("package PACKAGE;", &format!("package {pkg};")),
        }];
        for e in &model.enums {
            files.push(g.file(&e.flat, g.enum_class(e)));
        }
        for m in &model.messages {
            for o in &m.oneofs {
                files.push(g.file(&g.oneof_name(m, &o.name), g.oneof_class(m, o)));
            }
            files.push(g.file(&m.flat, g.message_class(m)));
        }
        Ok(files)
    }
}

struct Gen<'a> {
    model: &'a Model,
    pkg: &'a str,
}

fn ident(name: &str) -> String {
    avoid(name, KEYWORDS)
}

fn boxed(s: Scalar) -> &'static str {
    match s {
        Scalar::Bool => "Boolean",
        Scalar::Int32 | Scalar::UInt32 | Scalar::SInt32 | Scalar::Fixed32 | Scalar::SFixed32 => {
            "Integer"
        }
        Scalar::Int64 | Scalar::UInt64 | Scalar::SInt64 | Scalar::Fixed64 | Scalar::SFixed64 => {
            "Long"
        }
        Scalar::Float32 => "Float",
        Scalar::Float64 => "Double",
        Scalar::String => "String",
        Scalar::Bytes => "byte[]",
    }
}

fn primitive(s: Scalar) -> &'static str {
    match boxed(s) {
        "Boolean" => "boolean",
        "Integer" => "int",
        "Long" => "long",
        "Float" => "float",
        "Double" => "double",
        other => other,
    }
}

fn scalar_const(s: Scalar) -> String {
    format!("Tpt20Runtime.Scalar.{}", s.name().to_uppercase())
}

fn scalar_default_expr(s: Scalar) -> &'static str {
    match s {
        Scalar::Bool => "false",
        Scalar::Float32 => "0f",
        Scalar::Float64 => "0d",
        Scalar::String => "\"\"",
        Scalar::Bytes => "new byte[0]",
        Scalar::Int64 | Scalar::UInt64 | Scalar::SInt64 | Scalar::Fixed64 | Scalar::SFixed64 => {
            "0L"
        }
        _ => "0",
    }
}

impl Gen<'_> {
    fn file(&self, class: &str, body: String) -> GeneratedFile {
        GeneratedFile {
            path: format!("{}/{class}.java", self.pkg),
            contents: format!(
                "// Generated by tpt20-codegen-backends (java). DO NOT EDIT.\n// Schema package: {}\npackage {};\n\n{body}",
                self.model.package, self.pkg
            ),
        }
    }

    fn enum_default(&self, e: &Enum) -> i32 {
        e.values
            .iter()
            .find(|v| v.number == 0 && !v.alias)
            .or_else(|| e.values.first())
            .map(|v| v.number)
            .unwrap_or(0)
    }

    fn enum_class(&self, e: &Enum) -> String {
        let mut s = String::new();
        let _ = write!(
            s,
            "/** Enum `{}` ({}). Values are plain ints so unknown numbers survive. */\npublic final class {} {{\n    private {}() {{}}\n\n",
            e.full_name,
            if e.open { "open" } else { "closed" },
            e.flat,
            e.flat
        );
        for v in &e.values {
            let _ = writeln!(
                s,
                "    public static final int {} = {};",
                ident(&v.name),
                v.number
            );
        }
        let mut numbers: Vec<i32> = e.values.iter().map(|v| v.number).collect();
        numbers.sort_unstable();
        numbers.dedup();
        let cases: String = numbers.iter().map(|n| format!("case {n}: ")).collect();
        let _ = write!(
            s,
            "\n    /** Whether {{@code n}} is a declared value. */\n    public static boolean valid(int n) {{\n        switch (n) {{\n            {cases}return true;\n            default: return false;\n        }}\n    }}\n}}\n"
        );
        if numbers.is_empty() {
            s = s.replace(
                "switch (n) {\n            return true;\n            default: return false;\n        }",
                "return false;",
            );
        }
        s
    }

    fn oneof_name(&self, m: &Message, oneof: &str) -> String {
        format!("{}_{}", m.flat, pascal(oneof))
    }

    fn java_ty(&self, ty: Ty) -> String {
        match ty {
            Ty::Scalar(s) => boxed(s).to_string(),
            Ty::Enum(_) => "Integer".to_string(),
            Ty::Message(i) => self.model.messages[i].flat.clone(),
        }
    }

    fn oneof_class(&self, m: &Message, o: &crate::model::Oneof) -> String {
        let name = self.oneof_name(m, &o.name);
        let mut s = String::new();
        let _ = write!(
            s,
            "/** Oneof `{}.{}`; exactly one variant is set. */\npublic abstract class {name} {{\n    private {name}() {{}}\n",
            m.full_name, o.name
        );
        for f in &o.fields {
            let v = pascal(&f.name);
            let ty = match f.ty {
                Ty::Scalar(sc) => primitive(sc).to_string(),
                Ty::Enum(_) => "int".to_string(),
                Ty::Message(i) => self.model.messages[i].flat.clone(),
            };
            let _ = write!(
                s,
                "\n    /** Variant `{}` (field {}). */\n    public static final class {v} extends {name} {{\n        public final {ty} value;\n        public {v}({ty} value) {{ this.value = value; }}\n    }}\n",
                f.name, f.id
            );
        }
        s.push_str("}\n");
        s
    }

    fn field_decl(&self, f: &Field) -> String {
        let name = ident(&f.name);
        match f.card {
            Card::Implicit => match f.ty {
                Ty::Scalar(sc) => format!(
                    "public {} {name} = {};",
                    primitive(sc),
                    scalar_default_expr(sc)
                ),
                Ty::Enum(i) => format!(
                    "public int {name} = {};",
                    self.enum_default(&self.model.enums[i])
                ),
                Ty::Message(i) => format!("public {} {name};", self.model.messages[i].flat),
            },
            Card::Explicit => format!("public {} {name};", self.java_ty(f.ty)),
            Card::Repeated => format!(
                "public java.util.List<{}> {name} = new java.util.ArrayList<>();",
                self.java_ty(f.ty)
            ),
            Card::Map(k) => format!(
                "public java.util.Map<{}, {}> {name} = new java.util.LinkedHashMap<>();",
                boxed(k),
                self.java_ty(f.ty)
            ),
        }
    }

    /// Statement writing `expr` as field `id` into writer `w`.
    fn put(&self, w: &str, id: u32, ty: Ty, expr: &str) -> String {
        match ty {
            Ty::Scalar(s) => format!("{w}.putScalar({id}, {}, {expr});", scalar_const(s)),
            Ty::Enum(_) => format!("{w}.putEnum({id}, {expr});"),
            Ty::Message(_) => format!("{w}.putLen({id}, ({expr}).encode());"),
        }
    }

    fn message_class(&self, m: &Message) -> String {
        let mut s = String::new();
        let _ = write!(
            s,
            "/** Message `{}`. */\npublic final class {} {{\n",
            m.full_name, m.flat
        );
        for f in &m.fields {
            let _ = writeln!(s, "    {}", self.field_decl(f));
        }
        for o in &m.oneofs {
            let _ = writeln!(
                s,
                "    /** One of the variants of {}. */\n    public {} {};",
                self.oneof_name(m, &o.name),
                self.oneof_name(m, &o.name),
                ident(&o.name)
            );
        }
        s.push_str(
            "    /** Fields this schema does not know; they are re-encoded. */\n    public java.util.List<Tpt20Runtime.RawField> unknownFields = new java.util.ArrayList<>();\n",
        );
        s.push_str(&self.encode(m));
        s.push_str(&self.decode(m));
        s.push_str("}\n");
        s
    }

    fn encode(&self, m: &Message) -> String {
        let mut s = String::new();
        s.push_str("\n    /** Serializes the message to the native wire format. */\n    public byte[] encode() {\n        Tpt20Runtime.Writer w = new Tpt20Runtime.Writer();\n");
        for f in &m.fields {
            let a = ident(&f.name);
            match f.card {
                Card::Implicit => {
                    let cond = match f.ty {
                        Ty::Scalar(Scalar::Bool) => a.clone(),
                        Ty::Scalar(Scalar::String) => format!("!{a}.isEmpty()"),
                        Ty::Scalar(Scalar::Bytes) => format!("{a}.length > 0"),
                        Ty::Scalar(_) | Ty::Enum(_) => format!("{a} != 0"),
                        Ty::Message(_) => format!("{a} != null"),
                    };
                    let _ = writeln!(s, "        if ({cond}) {}", self.put("w", f.id, f.ty, &a));
                }
                Card::Explicit => {
                    let _ = writeln!(
                        s,
                        "        if ({a} != null) {}",
                        self.put("w", f.id, f.ty, &a)
                    );
                }
                Card::Repeated => match f.ty {
                    Ty::Scalar(sc) if sc.packable() => {
                        let _ = writeln!(
                            s,
                            "        if (!{a}.isEmpty()) w.putPacked({}, {}, {a});",
                            f.id,
                            scalar_const(sc)
                        );
                    }
                    Ty::Enum(_) => {
                        let _ = writeln!(
                            s,
                            "        if (!{a}.isEmpty()) w.putEnumPacked({}, {a});",
                            f.id
                        );
                    }
                    _ => {
                        let _ = writeln!(
                            s,
                            "        for ({} v : {a}) {}",
                            self.java_ty(f.ty),
                            self.put("w", f.id, f.ty, "v")
                        );
                    }
                },
                Card::Map(k) => {
                    let _ = writeln!(
                        s,
                        "        for ({} k : Tpt20Runtime.sortedKeys({a}, {})) {{\n            Tpt20Runtime.Writer e = new Tpt20Runtime.Writer();\n            {}\n            {}\n            w.putLen({}, e.toByteArray());\n        }}",
                        boxed(k),
                        scalar_const(k),
                        self.put("e", 1, Ty::Scalar(k), "k"),
                        self.put("e", 2, f.ty, &format!("{a}.get(k)")),
                        f.id
                    );
                }
            }
        }
        for o in &m.oneofs {
            let a = ident(&o.name);
            let oname = self.oneof_name(m, &o.name);
            for (i, f) in o.fields.iter().enumerate() {
                let kw = if i == 0 { "if" } else { "else if" };
                let v = pascal(&f.name);
                let _ = writeln!(
                    s,
                    "        {kw} ({a} instanceof {oname}.{v}) {}",
                    self.put("w", f.id, f.ty, &format!("(({oname}.{v}) {a}).value"))
                );
            }
        }
        s.push_str(
            "        w.putUnknown(unknownFields);\n        return w.toByteArray();\n    }\n",
        );
        s
    }

    /// Expression decoding occurrence `f` of `ty`.
    fn get(&self, ty: Ty, f: &str) -> String {
        match ty {
            Ty::Scalar(sc) => format!(
                "({}) Tpt20Runtime.getScalar({f}, {}, l)",
                boxed(sc),
                scalar_const(sc)
            ),
            Ty::Enum(i) => format!("Tpt20Runtime.getEnum({f}, {})", self.valid_ref(Ty::Enum(i))),
            Ty::Message(i) => format!(
                "{}.decode(Tpt20Runtime.getLen({f}), l, depth + 1)",
                self.model.messages[i].flat
            ),
        }
    }

    fn valid_ref(&self, ty: Ty) -> String {
        match ty {
            Ty::Enum(i) if !self.model.enums[i].open => {
                format!("{}::valid", self.model.enums[i].flat)
            }
            _ => "null".into(),
        }
    }

    fn decode(&self, m: &Message) -> String {
        let mut s = String::new();
        let name = &m.flat;
        let _ = write!(
            s,
            "\n    /** Parses bytes with the default limits. */\n    public static {name} decode(byte[] data) {{\n        return decode(data, Tpt20Runtime.defaultLimits(), 1);\n    }}\n\n    /** Parses bytes under explicit limits. */\n    public static {name} decode(byte[] data, Tpt20Runtime.Limits l) {{\n        return decode(data, l, 1);\n    }}\n\n    static {name} decode(byte[] data, Tpt20Runtime.Limits l, int depth) {{\n        Tpt20Runtime.checkDepth(depth, l);\n        {name} m = new {name}();\n        int unknown = 0;\n        for (Tpt20Runtime.RawField f : Tpt20Runtime.parseFields(data, l)) {{\n            int id = f.id > Integer.MAX_VALUE ? -1 : (int) f.id;\n            switch (id) {{\n"
        );
        for f in &m.fields {
            let a = format!("m.{}", ident(&f.name));
            let _ = writeln!(s, "                case {}: {{", f.id);
            match f.card {
                Card::Implicit | Card::Explicit => {
                    let _ = writeln!(s, "                    {a} = {};", self.get(f.ty, "f"));
                }
                Card::Repeated => match f.ty {
                    Ty::Scalar(sc) if sc.packable() => {
                        let _ = writeln!(
                            s,
                            "                    for (Object o : Tpt20Runtime.getPacked(f, {}, l)) {a}.add(({}) o);\n                    Tpt20Runtime.checkRepeated({a}.size(), l);",
                            scalar_const(sc),
                            boxed(sc)
                        );
                    }
                    Ty::Enum(_) => {
                        let _ = writeln!(
                            s,
                            "                    {a}.addAll(Tpt20Runtime.getEnumPacked(f, {}, l));\n                    Tpt20Runtime.checkRepeated({a}.size(), l);",
                            self.valid_ref(f.ty)
                        );
                    }
                    _ => {
                        let _ = writeln!(
                            s,
                            "                    {a}.add({});\n                    Tpt20Runtime.checkRepeated({a}.size(), l);",
                            self.get(f.ty, "f")
                        );
                    }
                },
                Card::Map(k) => {
                    let vdefault = match f.ty {
                        Ty::Scalar(sc) => scalar_default_expr(sc).to_string(),
                        Ty::Enum(i) => self.enum_default(&self.model.enums[i]).to_string(),
                        Ty::Message(i) => format!(
                            "{}.decode(new byte[0], l, depth + 1)",
                            self.model.messages[i].flat
                        ),
                    };
                    let _ = writeln!(
                        s,
                        "                    Tpt20Runtime.RawField[] e = Tpt20Runtime.mapEntry(Tpt20Runtime.getLen(f), l);\n                    {kb} key = e[0] == null ? {kd} : {kget};\n                    {vb} val = e[1] == null ? {vdefault} : {vget};\n                    {a}.put(key, val);\n                    Tpt20Runtime.checkMap({a}.size(), l);",
                        kb = boxed(k),
                        kd = scalar_default_expr(k),
                        kget = self.get(Ty::Scalar(k), "e[0]"),
                        vb = self.java_ty(f.ty),
                        vget = self.get(f.ty, "e[1]"),
                    );
                }
            }
            s.push_str("                    break;\n                }\n");
        }
        for o in &m.oneofs {
            let oname = self.oneof_name(m, &o.name);
            for f in &o.fields {
                let v = pascal(&f.name);
                let _ = writeln!(
                    s,
                    "                case {}:\n                    m.{} = new {oname}.{v}({});\n                    break;",
                    f.id,
                    ident(&o.name),
                    self.get(f.ty, "f")
                );
            }
        }
        s.push_str(
            "                default:\n                    unknown += Tpt20Runtime.unknownSize(f);\n                    if (unknown > l.maxUnknownFieldBytes) {\n                        throw new Tpt20Runtime.DecodeException(\"payload exceeded configured byte limit\");\n                    }\n                    m.unknownFields.add(f);\n            }\n        }\n        return m;\n    }\n",
        );
        s
    }
}
