//! Python backend: dataclasses + the minimal `tpt20_runtime` module.

use crate::model::{Card, Enum, Field, Message, Model, Scalar, Ty};
use crate::naming::{avoid, package_ident, pascal};
use crate::{Backend, BackendError, BackendOptions, GeneratedFile};
use std::fmt::Write;
use tpt20_ir as ir;

const RUNTIME: &str = include_str!("runtime/tpt20_runtime.py");
const RPC_RUNTIME: &str = include_str!("runtime/tpt20_rpc.py");

const KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield", "self", "cls", "match", "case", "type",
];

/// Python code generator.
#[derive(Debug, Clone, Copy, Default)]
pub struct PythonBackend;

impl Backend for PythonBackend {
    fn name(&self) -> &'static str {
        "python"
    }

    fn generate(
        &self,
        package: &ir::PackageIr,
        options: &BackendOptions,
    ) -> Result<Vec<GeneratedFile>, BackendError> {
        let model = Model::build(package)?;
        let module = options
            .package_name
            .clone()
            .unwrap_or_else(|| package_ident(&model.package, "schema"));
        let mut g = Gen {
            model: &model,
            out: String::new(),
        };
        g.file(&module);
        let mut files = vec![
            GeneratedFile {
                path: format!("{module}.py"),
                contents: g.out,
            },
            GeneratedFile {
                path: "tpt20_runtime.py".to_string(),
                contents: RUNTIME.to_string(),
            },
        ];
        if options.services && !model.services.is_empty() {
            let mut sg = Gen {
                model: &model,
                out: String::new(),
            };
            sg.services(&module);
            files.push(GeneratedFile {
                path: format!("{module}_services.py"),
                contents: sg.out,
            });
            files.push(GeneratedFile {
                path: "tpt20_rpc.py".to_string(),
                contents: RPC_RUNTIME.to_string(),
            });
        }
        Ok(files)
    }
}

struct Gen<'a> {
    model: &'a Model,
    out: String,
}

fn ident(name: &str) -> String {
    avoid(name, KEYWORDS)
}

fn scalar_default(s: Scalar) -> &'static str {
    match s {
        Scalar::Bool => "False",
        Scalar::Float32 | Scalar::Float64 => "0.0",
        Scalar::String => "\"\"",
        Scalar::Bytes => "b\"\"",
        _ => "0",
    }
}

fn scalar_hint(s: Scalar) -> &'static str {
    match s {
        Scalar::Bool => "bool",
        Scalar::Float32 | Scalar::Float64 => "float",
        Scalar::String => "str",
        Scalar::Bytes => "bytes",
        _ => "int",
    }
}

impl Gen<'_> {
    fn w(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn enum_default(&self, e: &Enum) -> i32 {
        e.values
            .iter()
            .find(|v| v.number == 0 && !v.alias)
            .or_else(|| e.values.first())
            .map(|v| v.number)
            .unwrap_or(0)
    }

    fn type_hint(&self, ty: Ty) -> String {
        match ty {
            Ty::Scalar(s) => scalar_hint(s).to_string(),
            Ty::Enum(_) => "int".to_string(),
            Ty::Message(i) => format!("\"{}\"", self.model.messages[i].flat),
        }
    }

    fn file(&mut self, module: &str) {
        self.w("# @generated by tpt20-codegen-backends (python) -- DO NOT EDIT.");
        let _ = writeln!(self.out, "# Schema package: {}", self.model.package);
        self.w("from __future__ import annotations");
        self.w("");
        self.w("import dataclasses");
        self.w("from typing import Any, Dict, List, Optional, Tuple");
        self.w("");
        self.w("import tpt20_runtime as rt");
        self.w("");
        let _ = module;
        for e in &self.model.enums {
            self.enum_class(e);
        }
        for m in &self.model.messages {
            self.message(m);
        }
    }

    fn enum_class(&mut self, e: &Enum) {
        let _ = write!(self.out, "\n\nclass {}:\n", e.flat);
        let _ = writeln!(
            self.out,
            "    \"\"\"Enum `{}` ({}).\"\"\"",
            e.full_name,
            if e.open { "open" } else { "closed" }
        );
        if e.values.is_empty() {
            self.w("    pass");
        }
        for v in &e.values {
            let _ = writeln!(self.out, "    {} = {}", ident(&v.name), v.number);
        }
        let numbers: Vec<String> = e.values.iter().map(|v| v.number.to_string()).collect();
        let _ = writeln!(
            self.out,
            "    NUMBERS = frozenset({{{}}})",
            numbers.join(", ")
        );
        if e.open {
            self.w("    VALID = None  # open enum: unknown numbers are preserved");
        } else {
            self.w("    VALID = NUMBERS");
        }
    }

    fn valid_expr(&self, ty: Ty) -> String {
        match ty {
            Ty::Enum(i) => format!("{}.VALID", self.model.enums[i].flat),
            _ => "None".into(),
        }
    }

    fn field_default(&self, f: &Field) -> String {
        match f.card {
            Card::Repeated => "dataclasses.field(default_factory=list)".into(),
            Card::Map(_) => "dataclasses.field(default_factory=dict)".into(),
            Card::Explicit => "None".into(),
            Card::Implicit => match f.ty {
                Ty::Scalar(s) => scalar_default(s).into(),
                Ty::Enum(i) => self.enum_default(&self.model.enums[i]).to_string(),
                Ty::Message(_) => "None".into(),
            },
        }
    }

    fn field_hint(&self, f: &Field) -> String {
        let base = self.type_hint(f.ty);
        match f.card {
            Card::Repeated => format!("List[{base}]"),
            Card::Map(k) => format!("Dict[{}, {base}]", scalar_hint(k)),
            Card::Explicit => format!("Optional[{base}]"),
            Card::Implicit => match f.ty {
                Ty::Message(_) => format!("Optional[{base}]"),
                _ => base,
            },
        }
    }

    fn variant_class(m: &Message, oneof: &str, field: &str) -> String {
        format!("{}_{}_{}", m.flat, pascal(oneof), pascal(field))
    }

    fn message(&mut self, m: &Message) {
        // Oneof variant holders first (referenced by annotations only as strings).
        for o in &m.oneofs {
            for f in &o.fields {
                let cls = Self::variant_class(m, &o.name, &f.name);
                let _ = write!(
                    self.out,
                    "\n\n@dataclasses.dataclass\nclass {cls}:\n    \"\"\"Oneof `{}.{}` holding `{}` (field {}).\"\"\"\n    value: {}\n    FIELD_ID = {}\n",
                    m.full_name,
                    o.name,
                    f.name,
                    f.id,
                    self.value_hint(f.ty),
                    f.id
                );
            }
        }

        let _ = write!(
            self.out,
            "\n\n@dataclasses.dataclass\nclass {}:\n    \"\"\"Message `{}`.\"\"\"\n",
            m.flat, m.full_name
        );
        for f in &m.fields {
            let _ = writeln!(
                self.out,
                "    {}: {} = {}",
                ident(&f.name),
                self.field_hint(f),
                self.field_default(f)
            );
        }
        for o in &m.oneofs {
            let variants: Vec<String> = o
                .fields
                .iter()
                .map(|f| format!("\"{}\"", Self::variant_class(m, &o.name, &f.name)))
                .collect();
            let _ = writeln!(
                self.out,
                "    {}: Optional[Any] = None  # one of: {}",
                ident(&o.name),
                variants.join(", ")
            );
        }
        self.w("    unknown_fields: List[Tuple[int, int, Any]] = dataclasses.field(default_factory=list)");

        self.encode_method(m);
        self.decode_method(m);
    }

    fn value_hint(&self, ty: Ty) -> String {
        match ty {
            Ty::Message(i) => format!("\"{}\"", self.model.messages[i].flat),
            Ty::Scalar(s) => scalar_hint(s).to_string(),
            Ty::Enum(_) => "int".to_string(),
        }
    }

    /// Statement writing `value_expr` as field `id` into `buf`.
    fn put(&self, buf: &str, id: u32, ty: Ty, value_expr: &str) -> String {
        match ty {
            Ty::Scalar(s) => format!("rt.put_scalar({buf}, {id}, \"{}\", {value_expr})", s.name()),
            Ty::Enum(_) => format!("rt.put_enum({buf}, {id}, {value_expr})"),
            Ty::Message(_) => format!("rt.write_len({buf}, {id}, {value_expr}.encode())"),
        }
    }

    fn encode_method(&mut self, m: &Message) {
        self.w("");
        self.w("    def encode(self) -> bytes:");
        self.w("        out = bytearray()");
        for f in &m.fields {
            let a = format!("self.{}", ident(&f.name));
            match f.card {
                Card::Implicit => {
                    let cond = match f.ty {
                        Ty::Enum(_) => format!("{a} != 0"),
                        Ty::Message(_) => format!("{a} is not None"),
                        Ty::Scalar(_) => a.clone(),
                    };
                    let stmt = self.put("out", f.id, f.ty, &a);
                    let _ = writeln!(self.out, "        if {cond}:\n            {stmt}");
                }
                Card::Explicit => {
                    let stmt = self.put("out", f.id, f.ty, &a);
                    let _ = writeln!(self.out, "        if {a} is not None:\n            {stmt}");
                }
                Card::Repeated => match f.ty {
                    Ty::Scalar(s) if s.packable() => {
                        let _ = writeln!(
                            self.out,
                            "        if {a}:\n            rt.put_packed(out, {}, \"{}\", {a})",
                            f.id,
                            s.name()
                        );
                    }
                    Ty::Enum(_) => {
                        let _ = writeln!(
                            self.out,
                            "        if {a}:\n            rt.put_enum_packed(out, {}, {a})",
                            f.id
                        );
                    }
                    _ => {
                        let stmt = self.put("out", f.id, f.ty, "v");
                        let _ = writeln!(self.out, "        for v in {a}:\n            {stmt}");
                    }
                },
                Card::Map(k) => {
                    let kput = format!("rt.put_scalar(entry, 1, \"{}\", k)", k.name());
                    let vput = self.put("entry", 2, f.ty, &format!("{a}[k]"));
                    let _ = writeln!(
                        self.out,
                        "        for k in rt.sorted_keys({a}):\n            entry = bytearray()\n            {kput}\n            {vput}\n            rt.write_len(out, {}, bytes(entry))",
                        f.id
                    );
                }
            }
        }
        for o in &m.oneofs {
            let a = format!("self.{}", ident(&o.name));
            let _ = writeln!(self.out, "        _o = {a}");
            for (i, f) in o.fields.iter().enumerate() {
                let cls = Self::variant_class(m, &o.name, &f.name);
                let kw = if i == 0 { "if" } else { "elif" };
                let stmt = self.put("out", f.id, f.ty, "_o.value");
                let _ = writeln!(
                    self.out,
                    "        {kw} isinstance(_o, {cls}):\n            {stmt}"
                );
            }
        }
        self.w("        rt.put_unknown(out, self.unknown_fields)");
        self.w("        return bytes(out)");
    }

    /// Expression decoding a scalar/enum/message occurrence.
    fn get(&self, id: u32, ty: Ty, depth: &str) -> String {
        match ty {
            Ty::Scalar(s) => format!("rt.get_scalar({id}, wc, val, \"{}\", limits)", s.name()),
            Ty::Enum(_) => format!("rt.get_enum({id}, wc, val, {})", self.valid_expr(ty)),
            Ty::Message(i) => format!(
                "{}._decode(rt.get_len({id}, wc, val), limits, {depth})",
                self.model.messages[i].flat
            ),
        }
    }

    fn decode_method(&mut self, m: &Message) {
        self.w("");
        self.w("    @classmethod");
        self.w(&format!(
            "    def decode(cls, data: bytes, limits: Optional[rt.Limits] = None) -> \"{}\":",
            m.flat
        ));
        self.w("        return cls._decode(bytes(data), limits or rt.DEFAULT_LIMITS, 1)");
        self.w("");
        self.w("    @classmethod");
        self.w("    def _decode(cls, data: bytes, limits: rt.Limits, depth: int):");
        self.w("        rt.check_depth(depth, limits)");
        self.w("        m = cls()");
        self.w("        unknown_bytes = 0");
        self.w("        for fid, wc, val in rt.parse_fields(data, limits):");
        let mut first = true;
        let kw = |first: &mut bool| {
            let k = if *first { "if" } else { "elif" };
            *first = false;
            k
        };
        for f in &m.fields {
            let k = kw(&mut first);
            let a = format!("m.{}", ident(&f.name));
            let _ = writeln!(self.out, "            {k} fid == {}:", f.id);
            match f.card {
                Card::Implicit | Card::Explicit => {
                    let e = self.get(f.id, f.ty, "depth + 1");
                    let _ = writeln!(self.out, "                {a} = {e}");
                }
                Card::Repeated => match f.ty {
                    Ty::Scalar(s) if s.packable() => {
                        let _ = writeln!(
                            self.out,
                            "                {a}.extend(rt.get_packed({}, wc, val, \"{}\", limits))\n                rt.check_repeated(len({a}), limits)",
                            f.id,
                            s.name()
                        );
                    }
                    Ty::Enum(_) => {
                        let _ = writeln!(
                            self.out,
                            "                {a}.extend(rt.get_enum_packed({}, wc, val, {}, limits))\n                rt.check_repeated(len({a}), limits)",
                            f.id,
                            self.valid_expr(f.ty)
                        );
                    }
                    _ => {
                        let e = self.get(f.id, f.ty, "depth + 1");
                        let _ = writeln!(
                            self.out,
                            "                {a}.append({e})\n                rt.check_repeated(len({a}), limits)"
                        );
                    }
                },
                Card::Map(k) => {
                    let kdefault = scalar_default(k);
                    let vdefault = match f.ty {
                        Ty::Scalar(s) => scalar_default(s).to_string(),
                        Ty::Enum(i) => self.enum_default(&self.model.enums[i]).to_string(),
                        Ty::Message(i) => format!(
                            "{}._decode(b\"\", limits, depth + 1)",
                            self.model.messages[i].flat
                        ),
                    };
                    let vget = match f.ty {
                        Ty::Scalar(s) => {
                            format!("rt.get_scalar(2, ve[0], ve[1], \"{}\", limits)", s.name())
                        }
                        Ty::Enum(_) => {
                            format!("rt.get_enum(2, ve[0], ve[1], {})", self.valid_expr(f.ty))
                        }
                        Ty::Message(i) => format!(
                            "{}._decode(rt.get_len(2, ve[0], ve[1]), limits, depth + 1)",
                            self.model.messages[i].flat
                        ),
                    };
                    let _ = writeln!(
                        self.out,
                        "                ke, ve = rt.map_entry_fields(rt.get_len({id}, wc, val), limits)\n                key = {kdefault} if ke is None else rt.get_scalar(1, ke[0], ke[1], \"{kname}\", limits)\n                {a}[key] = {vdefault} if ve is None else {vget}\n                rt.check_map(len({a}), limits)",
                        id = f.id,
                        kname = k.name(),
                    );
                }
            }
        }
        for o in &m.oneofs {
            for f in &o.fields {
                let k = kw(&mut first);
                let cls = Self::variant_class(m, &o.name, &f.name);
                let e = self.get(f.id, f.ty, "depth + 1");
                let _ = writeln!(
                    self.out,
                    "            {k} fid == {}:\n                m.{} = {cls}({e})",
                    f.id,
                    ident(&o.name)
                );
            }
        }
        let k = if first { "if True" } else { "else" };
        let _ = writeln!(
            self.out,
            "            {k}:\n                unknown_bytes += rt.unknown_size(wc, val)\n                if unknown_bytes > limits.max_unknown_field_bytes:\n                    raise rt.DecodeError(\"payload exceeded configured byte limit\")\n                m.unknown_fields.append((fid, wc, val))"
        );
        self.w("        return m");
    }

    fn services(&mut self, module: &str) {
        self.w("# @generated by tpt20-codegen-backends (python) -- DO NOT EDIT.");
        self.w("# Service clients and servers; needs the `h2` package (see tpt20_rpc.py).");
        self.w("from __future__ import annotations");
        self.w("");
        self.w("import asyncio");
        self.w("import inspect");
        self.w("");
        self.w("import tpt20_rpc as rpc");
        self.w("import tpt20_runtime as rt");
        let _ = writeln!(self.out, "from {module} import *  # noqa: F401,F403");
        for s in &self.model.services {
            self.service(s);
        }
    }

    fn service(&mut self, s: &crate::model::Service) {
        let full = if self.model.package.is_empty() {
            s.name.clone()
        } else {
            format!("{}.{}", self.model.package, s.name)
        };
        let cls = pascal(&s.name);
        let msg = |i: usize| self.model.messages[i].flat.clone();
        // Helpers shared by client and server (once per service, prefixed).
        let _ = write!(
            self.out,
            "\n\ndef _decode_{cls}(cls, data, what):\n    try:\n        return cls.decode(data)\n    except rt.DecodeError as e:\n        code = rpc.INVALID_ARGUMENT if what == \"request\" else rpc.INTERNAL\n        raise rpc.RpcError(code, \"invalid %s message: %s\" % (what, e))\n"
        );
        // Client.
        let _ = write!(
            self.out,
            "\n\nclass {cls}Client:\n    \"\"\"Client for service `{full}`.\"\"\"\n\n    NAME = {full:?}\n\n    def __init__(self, channel):\n        self.channel = channel\n"
        );
        for m in &s.methods {
            let fname = self.py_method(&m.name);
            let (q, r) = (msg(m.request), msg(m.response));
            let path = format!("{full}/{}", m.name);
            match (m.client_streaming, m.server_streaming) {
                (false, false) => {
                    let _ = write!(
                        self.out,
                        "\n    async def {fname}(self, request, metadata=None, timeout=None):\n        data = await self.channel.unary({path:?}, request.encode(), metadata, timeout)\n        return _decode_{cls}({r}, data, \"response\")\n"
                    );
                }
                (false, true) => {
                    let _ = write!(
                        self.out,
                        "\n    async def {fname}(self, request, metadata=None, timeout=None):\n        call = await self.channel.start({path:?}, metadata, timeout)\n        try:\n            await call.send(request.encode())\n            await call.close_send()\n            while True:\n                data = await call.recv()\n                if data is None:\n                    break\n                yield _decode_{cls}({r}, data, \"response\")\n        finally:\n            call.close()\n"
                    );
                }
                (true, false) => {
                    let _ = write!(
                        self.out,
                        "\n    async def {fname}(self, requests, metadata=None, timeout=None):\n        call = await self.channel.start({path:?}, metadata, timeout)\n        try:\n            async for request in rpc.aiter_of(requests):\n                await call.send(request.encode())\n            await call.close_send()\n            data = await call.recv()\n            if data is None:\n                raise rpc.RpcError(rpc.INTERNAL, \"call succeeded without a response message\")\n            if await call.recv() is not None:\n                raise rpc.RpcError(rpc.INTERNAL, \"unary call returned several messages\")\n            return _decode_{cls}({r}, data, \"response\")\n        finally:\n            call.close()\n"
                    );
                }
                (true, true) => {
                    let _ = write!(
                        self.out,
                        "\n    async def {fname}(self, requests, metadata=None, timeout=None):\n        call = await self.channel.start({path:?}, metadata, timeout)\n\n        async def pump():\n            async for request in rpc.aiter_of(requests):\n                await call.send(request.encode())\n            await call.close_send()\n\n        sender = asyncio.ensure_future(pump())\n        try:\n            while True:\n                data = await call.recv()\n                if data is None:\n                    break\n                yield _decode_{cls}({r}, data, \"response\")\n        finally:\n            sender.cancel()\n            call.close()\n"
                    );
                }
            }
            let _ = q;
        }
        // Server base class.
        let _ = write!(
            self.out,
            "\n\nclass {cls}Base:\n    \"\"\"Subclass and override the methods of service `{full}`.\n\n    Unary and client-streaming methods return the response; server-streaming and\n    bidi methods return (or are) an iterator of responses; client-streaming and\n    bidi methods receive an async iterator of requests.\n    \"\"\"\n"
        );
        for m in &s.methods {
            let fname = self.py_method(&m.name);
            let arg = if m.client_streaming {
                "requests"
            } else {
                "request"
            };
            let _ = write!(
                self.out,
                "\n    async def {fname}(self, {arg}, ctx):\n        raise rpc.RpcError(rpc.UNIMPLEMENTED, \"method {} not implemented\")\n",
                m.name
            );
        }
        // Dispatcher + registration.
        let _ = write!(
            self.out,
            "\n\nasync def _requests_{cls}(call, cls):\n    while True:\n        data = await call.recv()\n        if data is None:\n            return\n        yield _decode_{cls}(cls, data, \"request\")\n\n\ndef register_{lc}(server, impl):\n    \"\"\"Adds `{full}` to a tpt20_rpc.Server.\"\"\"\n\n    async def dispatch(method, call, ctx):\n",
            lc = self.py_method(&s.name)
        );
        for m in &s.methods {
            let fname = self.py_method(&m.name);
            let (q, _r) = (msg(m.request), msg(m.response));
            let body = match (m.client_streaming, m.server_streaming) {
                (false, false) => format!(
                    "        data = await call.recv()\n            request = _decode_{cls}({q}, b\"\" if data is None else data, \"request\")\n            response = await impl.{fname}(request, ctx)\n            await call.send(response.encode())"
                ),
                (false, true) => format!(
                    "        data = await call.recv()\n            request = _decode_{cls}({q}, b\"\" if data is None else data, \"request\")\n            result = impl.{fname}(request, ctx)\n            if inspect.isawaitable(result):\n                result = await result\n            async for response in rpc.aiter_of(result):\n                await call.send(response.encode())"
                ),
                (true, false) => format!(
                    "        response = await impl.{fname}(_requests_{cls}(call, {q}), ctx)\n            await call.send(response.encode())"
                ),
                (true, true) => format!(
                    "        result = impl.{fname}(_requests_{cls}(call, {q}), ctx)\n            if inspect.isawaitable(result):\n                result = await result\n            async for response in rpc.aiter_of(result):\n                await call.send(response.encode())"
                ),
            };
            let _ = write!(
                self.out,
                "        if method == {:?}:\n    {body}\n            return\n",
                m.name
            );
        }
        let _ = write!(
            self.out,
            "        raise rpc.RpcError(rpc.UNIMPLEMENTED, \"unknown method `%s`\" % method)\n\n    server.register({full:?}, dispatch)\n"
        );
    }

    /// snake_case method name (`GetHTTPStatus` -> `get_http_status`).
    fn py_method(&self, name: &str) -> String {
        let chars: Vec<char> = name.chars().collect();
        let mut out = String::new();
        for (i, &c) in chars.iter().enumerate() {
            if c.is_uppercase() {
                let prev_lower =
                    i > 0 && (chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit());
                let next_lower = chars.get(i + 1).is_some_and(|n| n.is_lowercase());
                if i > 0 && (prev_lower || (chars[i - 1].is_uppercase() && next_lower)) {
                    out.push('_');
                }
                out.extend(c.to_lowercase());
            } else {
                out.push(c);
            }
        }
        ident(&out)
    }
}
