[package]
name = "descriptor-decoder"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Fuzz target for descriptor decoder"

[[bin]]
name = "fuzz_target"
path = "fuzz_targets/fuzz_target.rs"

[dependencies]
tpt20-descriptor = { path = "../../compiler/tpt20-descriptor" }
libfuzzer-sys = "0.4"
arbitrary = "1.3"
